### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by pms1969** [samsung-cnct/chart-dex#5]
```
$ helm repo add cnct http://atlas.cnct.io 
Error: Looks like "http://atlas.cnct.io" is not a valid chart repository or cannot be reached: Failed to fetch http://atlas.cnct.io/index.yaml : 404 Not Found
```

If I try and navigate to that url, I get
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>
```

**Comment by notjames** [comment]
Ah yes! That repo was recently taken down. Looks like our documentation needs to be updated. 

use `helm registry install quay.io/samsung_cnct/dex`

**Comment by pms1969** [comment]
Thanks @notjames that seems to have done the trick.  although now I need to get the config right :-)

**Comment by notjames** [comment]
@pms1969 yeah, you'll need to create a values.yaml file. When you do a helm install, the chart is placed in /tmp. You can look through that to get the default values file and tweak til your heart's content.
